#include(utils)
#detect_installed_gpus(COMPUTE_CAPABILITY)
#message(${COMPUTE_CAPABILITY})

set(LEGION_NAME legion)

# TODO fix python version
message(STATUS "Building ${LEGION_NAME}")
ExternalProject_Add(${LEGION_NAME}
 SOURCE_DIR ${PROJECT_SOURCE_DIR}/legion
 PREFIX ${LEGION_NAME}
 INSTALL_DIR ${LEGION_NAME}/install
 CONFIGURE_COMMAND ${CMAKE_COMMAND}
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
   -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF
   -DLegion_USE_CUDA=ON
   -DLegion_MAX_DIM=4
   -DLegion_BUILD_EXAMPLES=OFF
   -DLegion_BUILD_APPS=OFF
   -DLegion_CUDA_ARCH=60
   -DLegion_USE_Python=${LEGION_USE_PYTHON}
   -DLegion_Python_Version=3.6
   <SOURCE_DIR>
)

ExternalProject_get_property(${LEGION_NAME} INSTALL_DIR)
install(DIRECTORY ${INSTALL_DIR}/ DESTINATION ${CMAKE_INSTALL_PREFIX} USE_SOURCE_PERMISSIONS)