set(NCCL_NAME nccl)
set(CUDA_ROOT $ENV{CUDA_ROOT})

find_package(CUDA REQUIRED)

ExternalProject_Add(${NCCL_NAME}
 SOURCE_DIR ${PROJECT_SOURCE_DIR}/nccl
 PREFIX ${NCCL_NAME}
 INSTALL_DIR ${NCCL_NAME}/install
 CONFIGURE_COMMAND ""
 BUILD_COMMAND make src.build "CUDA_HOME=${CUDA_ROOT}" 
 BUILD_IN_SOURCE 1
)